#pragma once

#include "buffer_resource.h"
#include "command_buffer_resource.h"
#include "fence_resource.h"
#include "framebuffer_resource.h"
#include "graphics_pipeline_resource.h"
#include "image_resource.h"
#include "image_view_resource.h"
#include "material_layout_resource.h"
#include "material_resource.h"
#include "render_pass_object_resource.h"
#include "semaphore_resource.h"
#include "shader_resource.h"
#include "texture_resource.h"